RestaurantManager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('stock/', include('stock.urls', namespace='stock')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls', namespace='login')),
    path('', RedirectView.as_view(url='login/')),
]

backend/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('register/', views.register_view, name='register_view'),
    path('mainmenu/', views.mainmenu_view, name='mainmenu_view'),
]

backend/stock/urls.py
from django.urls import path
from . import views

app_name='stock'

urlpatterns = [
    path('', views.index, name='supply_index'),
    path('<int:supply_id>/', views.detail, name='supply_detail'),
    path('restock/', views.restock_ingredient, name='restock_ingredient'),
    path('restock/<int:supply_id>/', views.restock_specific, name='restock_specific'),
    path('search_menu/', views.search_ingredient, name='search_supply'),
    path('add/', views.addSupply, name='add_supply'),
    path('delete/<int:supply_id>/', views.deleteSupply, name='delete_supply')
]

backend/stock/models.py
from django.db import models
from login.models import Company
from django.urls import reverse

#TODO: ADD CUSTOM MANAGERS WHERE HELPFUL
#custom managers

#TODO: ADD get_absolute_url() METHOD WHERE NECESSARY

class Recipe(models.Model):
    recipe_id = models.BigAutoField('recipe id', primary_key=True)
    restaurant = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='restaurant')
    instructions = models.CharField('instructions', max_length=5000)
    recipe_name = models.CharField('recipe name', max_length=100)

    #is it helpful for these to be ordered?
    #I remember chef saying it would be helpful to have a gui, so it WOULD be helpful to order these
    class Meta:
        indexes = [models.Index(fields=['recipe_name'])]
        ordering = ['-recipe_name']
        verbose_name = 'recipe'
        verbose_name_plural = 'recipes'

    def __str__(self):
        return self.recipe_name

#supplies are ordered by name
class Supply(models.Model):
    SUPPLY_TYPE = (
        ('INGREDIENT', 'used as an ingredient'),
        ('MATERIAL', 'not used as an ingredient')
    )

    supply_id = models.BigAutoField('supply id', primary_key=True)
    restaurant = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='restaurant')
    storage_location = models.CharField('storage location', max_length=20)
    quantity = models.IntegerField('quantity')
    quantity_units = models.CharField('units', max_length=20) #gallons vs liters vs pounds etc.
    resupply = models.BooleanField('in stock')
    supply_name = models.CharField('supply name', max_length=5000)
    supply_type = models.CharField(choices=SUPPLY_TYPE, max_length=20, verbose_name='supply type')
    supply_description = models.CharField('supply description', max_length=5000, default='')

    class Meta:
        indexes = [models.Index(fields=['supply_name'])]
        ordering = ['-supply_name']
        verbose_name = 'supply'
        verbose_name_plural = 'supplies'

    def __str__(self):
        return self.supply_name
    
    def get_absolute_url(self):
        return reverse('stock:supply_detail', args=[self.supply_id])

#shipments are ordered by order date
class Shipment(models.Model):
    tracking_number = models.BigIntegerField('tracking number', primary_key=True)
    description = models.CharField('shipment description', max_length=500)
    restaurant = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='restaurant')
    ordered = models.DateTimeField('order date')
    expected = models.DateTimeField('expected arrival')
    delivered = models.DateTimeField('recorded delivery')

    class Meta:
        indexes = [models.Index(fields=['ordered'])]
        ordering = ['-ordered']
        verbose_name = 'shipment'
        verbose_name_plural = 'shipments'

    def __str__(self):
        return self.tracking_number

#since this is a join table, it probably shouldn't have a str method, that'd be kinda weird
class RecipeSupply(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, verbose_name='recipe id')
    supply = models.ForeignKey(Supply, on_delete=models.CASCADE, verbose_name='supply id')
    amount = models.FloatField('amount')

    #join the recipe and supply as a joint primary key
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['recipe', 'supply'], name='unique_recipe_supply')
        ]
        verbose_name = 'recipe supply association'
        verbose_name_plural = 'recipe supply associations'

#Same as recipe supply, probably shouldnt have a str method
class ShipmentSupply(models.Model):
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE, verbose_name='shipment number')
    supply = models.ForeignKey(Supply, on_delete=models.CASCADE, verbose_name='supply id')
    amount = models.IntegerField('amount')

    #join the shipment and supply as a joint primary key
    class Meta:
        constraints = [
            models.UniqueConstraint(fields = ['shipment', 'supply'], name='unique_shipment_supply')
        ]
        verbose_name = 'active shipment supply association'
        verbose_name_plural = 'active shipment supply associations'

class RestockRecord(models.Model):
    supply = models.ForeignKey(Supply, on_delete=models.CASCADE)
    added_quantity = models.PositiveIntegerField()
    date_restocked = models.DateTimeField(auto_now_add=True)

    def supply_name(self):
        return self.supply.supply_name

stock/models.py
from django.db import models

# Create your models here.

backend/stock/forms.py
from django import forms
from .models import RestockRecord, Supply

class AddForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = ['supply_name', 'storage_location', 'quantity', 'quantity_units', 'supply_description', 'supply_type', 'resupply', 'restaurant']

class RestockForm(forms.ModelForm):
    class Meta:
        model = RestockRecord
        fields = ['supply', 'added_quantity']

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=500, required=False)

    

backend/stock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Supply
from .forms import RestockForm, SearchForm, AddForm

#TODO: ENSURE URLS ARE WORKING AS INTENDED

#TODO: MAKE THIS WORK WITH THE NEW DATABASE SCHEMA
#TODO: SEPARATE INGREDIENTS AND SUPPLIES (not important rn)
def addSupply(request):
    if request.method == "POST":
        form = AddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('stock:search_supply')
    else:
        form = AddForm()

    return render(request, 'stock/add_supply.html', {'form': form})

def deleteSupply(request, supply_id):
    supply = get_object_or_404(Supply, pk=supply_id)

    if request.method == 'POST':
        supply.delete()
        return redirect('stock:search_supply')

    return render(request, 'stock/delete_supply.html', {'supply': supply})

def index(request):
    ingredients = Supply.objects.all()
    return render(request, 'stock/supplies.html', {'ingredients': ingredients})


def detail(request, supply_id):
    supply = get_object_or_404(Supply, pk=supply_id)
    return render(request, 'stock/detail.html', {'supply': supply})


def restock_ingredient(request):
    if request.method == "POST":
        form = RestockForm(request.POST)
        if form.is_valid():
            restock_record = form.save()
            supply = restock_record.supply
            supply.quantity += restock_record.added_quantity
            supply.save()
            return redirect('stock:search_supply')
    else:
        form = RestockForm()
    return render(request, 'stock/restock.html', {'form': form})


def restock_specific(request, supply_id):
    if request.method == "POST":
        form = RestockForm(request.POST)
        if form.is_valid():
            restock_record = form.save()
            supply = restock_record.supply
            supply.quantity += restock_record.added_quantity
            supply.save()
            return redirect('stock:search_supply')
    else:
        if supply_id:
            supply = get_object_or_404(Supply, pk=supply_id)
            form = RestockForm(initial={'supply': supply})
        else:
            form = RestockForm()
    return render(request, 'stock/restock.html', {'form': form})
            

def search_ingredient(request):
    form = SearchForm(request.GET)
    ingredients = Supply.objects.all()

    if form.is_valid() and form.cleaned_data['search_term']:
        search_term = form.cleaned_data['search_term']
        ingredients = Supply.objects.filter(supply_name__icontains=search_term)

    return render(request, 'stock/search_menu.html', {'form': form, 'ingredients': ingredients})

stock/views.py
from django.shortcuts import render

# Create your views here.

backend/stock/templates/stock/add_supply.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Form</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #e6f2e6; /* Light green background */
        }

        .container {
            width: 97%;
            padding: 20px;
            margin: auto; /* Center the container */
        }

        /* Form styling */
        form {
            background-color: #f7fff7; /* Very light green background */
            padding: 20px;
            border-radius: 5px;
            border: 1px solid #98bf98; /* Soft green border */
        }

        /* Button styling */
        .form-button {
            background-color: #346534; /* Dark green background */
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }

        .form-button:hover {
            background-color: #4e804e; /* Lighter green on hover */
        }

        /* Button container */
        .form-actions {
            padding-top: 10px; /* Space above buttons */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Add Items</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-actions">
                <button type="submit" class="form-button">Add</button>
                <a href="{% url 'stock:search_supply' %}" class="form-button">Back to Menu</a>
            </div>
        </form>
    </div>
</body>
</html>

backend/stock/templates/stock/delete_supply.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta viewport="width=device-width, initial-scale=1.0">
    <title>Delete {{ supply.supply_name }}?</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        .detail-container {
            background-color: white;
            border: 1px solid #346534; /* Dark forest green */
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 600px;
            margin: auto;
        }

        .detail-container h1 {
            color: #346534; /* Dark forest green */
            font-size: 28px;
            text-align: center;
        }

        .detail-list {
            list-style: none;
            padding: 0;
        }

        .detail-list li {
            margin-bottom: 10px;
            font-size: 16px;
            color: #555;
        }

        .detail-list b {
            color: #333;
        }

        .back-button, button.back-button {
            display: inline-block;
            background-color: #346534; /* Dark forest green */
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 16px;
            border-radius: 4px;
            margin-top: 20px;
            transition: background-color 0.3s;
            border: none; /* Removes default border for button */
            cursor: pointer; /* Changes cursor to pointer on hover */
        }

        .back-button:hover, button.back-button:hover {
            background-color: #4e804e; /* Slightly darker green */
        }
    </style>
</head>
<body>
    <div class="detail-container">
        <h1>Delete {{ supply.supply_name }}?</h1>
        <form method="post" action="{% url 'stock:delete_supply' supply.supply_id %}">
            {% csrf_token %}
            <a href="{% url 'stock:supply_detail' supply.supply_id %}" class="back-button">Cancel</a>
            <button type="submit" class="back-button">Delete</button>
        </form>
        
        
    </div>
</body>
</html>

backend/stock/templates/stock/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta viewport="width=device-width, initial-scale=1.0">
    <title>{{ supply.supply_name }} Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        .detail-container {
            background-color: white;
            border: 1px solid #346534; /* Dark forest green */
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 600px;
            margin: auto;
        }

        .detail-container h1 {
            color: #346534; /* Dark forest green */
            font-size: 28px;
            text-align: center;
        }

        .detail-list {
            list-style: none;
            padding: 0;
        }

        .detail-list li {
            margin-bottom: 10px;
            font-size: 16px;
            color: #555;
        }

        .detail-list b {
            color: #333;
        }

        .back-button, .right-button {
            display: inline-block;
            background-color: #346534; /* Dark forest green */
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 16px;
            border-radius: 4px;
            margin-top: 20px;
            transition: background-color 0.3s;
        }

        .back-button:hover, .right-button:hover {
            background-color: #4e804e; /* Slightly darker green */
        }

        .right-button {
            float: right; /* Aligns the button to the right */
        }

        /* Clear float */
        .detail-container:after {
            content: "";
            display: block;
            clear: both;
        }
    </style>
</head>
<body>
    <div class="detail-container">
        <h1>{{ supply.supply_name }}</h1>
        <ul class="detail-list">
            <li><b>Location</b>: {{ supply.storage_location }}</li>
            <li><b>Amount</b>: {{ supply.quantity }} {{ supply.quantity_units }}</li>
        </ul>
        <a href="{% url 'stock:search_supply' %}" class="back-button">Back</a>
        <a href="{% url 'stock:restock_specific' supply_id=supply.supply_id %}" class="back-button">Restock</a>
        <a href="{% url 'stock:delete_supply' supply.supply_id %}" class="right-button">Delete</a>
    </div>
</body>
</html>

backend/stock/templates/stock/restock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restock Form</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #e6f2e6; /* Light green background */
        }

        .container {
            width: 97%;
            padding: 20px;
            margin: auto; /* Center the container */
        }

        /* Form styling */
        form {
            background-color: #f7fff7; /* Very light green background */
            padding: 20px;
            border-radius: 5px;
            border: 1px solid #98bf98; /* Soft green border */
        }

        /* Input and button styling */
        input[type="submit"] {
            background-color: #346534; /* Dark green background */
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #4e804e; /* Lighter green on hover */
        }

        /* Paragraph (p) styling for form elements */
        p {
            margin: 10px 0;
        }

        .form-button {
            background-color: #346534; /* Dark green background */
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }

        .form-button:hover {
            background-color: #4e804e; /* Lighter green on hover */
        }

        /* Button container */
        .button-container {
            text-align: left;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Restock Items</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-container">
                <input type="submit" class="form-button" value="Restock">
                <a href="{% url 'stock:search_supply' %}" class="form-button">Back to Menu</a>
            </div>
        </form>
    </div>
</body>
</html>

backend/stock/templates/stock/search_menu.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile and Search Page</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #e6f2e6; /* Light green background */
        }

        .container {
            width: 97%;
            padding: 20px;
            position: relative;
        }

        /* Style for the big header title */
        .header-title {
            text-align: center; /* Center the title */
            font-size: 30px; /* Big font size */
            margin-top: 20px; /* Space from the top of the page */
            color: #346534; /* Color of the title, matching the theme */
        }

        /* Profile button styling */
        .profile-btn {
            position: absolute;
            top: 10px;
            right: 10px;
            display: flex;
            align-items: center;
            padding: 10px;
            border: 1px solid #98bf98; /* Soft green border */
            border-radius: 5px;
            cursor: pointer;
            background-color: #f7fff7; /* Very light green background */
        }

        .profile-btn img {
            width: 30px;
            height: 30px;
            border-radius: 50%;
            margin-right: 10px;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            top: 60px;
            right: 10px;
            border: 1px solid #98bf98; /* Soft green border */
            background-color: #f7fff7; /* Very light green background */
            padding: 10px;
            width: 200px;
            border-radius: 5px;
            z-index: 1;
        }

        /* Search section styling */
        .search-section {
            margin-top: 0px;
        }

        .output-box {
            width: 100%;
            height: calc(100vh - 200px);
            border: 1px solid #98bf98; /* Soft green border */
            overflow-y: auto; /* Enables vertical scrolling if content overflows */
            padding: 10px;
            margin-top: 10px;
            background-color: #fff; /* White background for contrast */
        }

        /* Recipe card styling */
        .recipe-card {
            border: 1px solid #ccc;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .logout-btn {
            display: block;
            background-color: #346534; /* Dark green background */
            color: white;
            text-align: center;
            border-radius: 5px;
            padding: 10px;
            margin-top: 10px;
            cursor: pointer;
            text-decoration: none; /* Remove underline from link */
        }

        .logout-btn:hover {
            background-color: #4e804e; /* Lighter green on hover */
        }

        .button-group {
            text-align: center; /* Center the button group */
            position: relative; /* Relative positioning within the container */
            padding-top: 20px; /* Space above the button group */
        }

        .center-btn {
            display: inline-block; /* Place buttons side by side */
            background-color: #346534; /* Dark green background */
            color: white;
            text-align: center;
            border-radius: 5px;
            padding: 10px 20px;
            margin: 0 10px; /* Space around each button */
            cursor: pointer;
            text-decoration: none; /* Remove underline from link */
            width: 100px; /* Fixed width */
            transition: background-color 0.3s ease;
        }

        .center-btn:hover {
            background-color: #4e804e; /* Lighter green on hover */
        }
    </style>
</head>

<body>

    <div class="container">

        <h1 class="header-title">Inventory Manager</h1>

        <!-- Profile Button with Dropdown -->
        <div class="profile-btn" onclick="toggleDropdown()">
            <img src="https://www.cpp.edu/it/img/student-page/cppmobileapptxtfixed1.jpg" alt="Profile Picture">
            Profile
            <div id="dropdownContent" class="dropdown-content">
                <p>{{ user }}</p>
                <p>{{ user.username }}</p>
                <p>{{ user.email }}</p>
                <!-- Logout Button -->
                <a href="{% url 'login:login_view' %}" class="logout-btn">Log Out</a>
            </div>
        </div>

        <div class="button-group">
            <a href="{% url 'stock:restock_ingredient' %}" class="center-btn">Restock</a>
            <a href="{% url 'stock:add_supply' %}" class="center-btn">Add Supply</a>
        </div>

        <!-- Search Section -->
        <div class="search-section">
            <form method="get" action="{% url 'stock:search_supply' %}">
                {{ form.as_p }}
                <button type="submit">Search</button>
            </form>
            <!-- Output Box with recipe cards -->
            <div class="output-box">
                <!-- Example Recipe Card -->
                {% for ingredient in ingredients %}
                <div class="recipe-card">
                    <h4><a href='{{ ingredient.get_absolute_url }}'>{{ ingredient.supply_name }}</a></h4>
                    <p>{{ingredient.supply_description}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        function toggleDropdown() {
            var dropdown = document.getElementById("dropdownContent");
            dropdown.style.display = dropdown.style.display === "none" ? "block" : "none";
        }

        // Close the dropdown if clicked outside
        window.onclick = function(event) {
            var dropdown = document.getElementById("dropdownContent");
            if (!event.target.matches('.profile-btn, .profile-btn *')) {
                dropdown.style.display = "none";
            }
        }
    </script>
    
</body>
    
</html>
    

backend/stock/templates/stock/supplies.html
{% for ingredient in ingredients %}
    <li><a href='{{ ingredient.get_absolute_url }}'>{{ ingredient.supply_name }}</a></li>
{% endfor %}
<a href="{% url 'stock:restock_ingredient' %}">Restock</a>